# Generated by Django 4.0.3 on 2022-03-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='imageUrl',
            field=models.URLField(default='https://cdn.discordapp.com/attachments/432564281113051136/952995078912241674/819133564.gif'),
        ),
        migrations.AlterField(
            model_name='star',
            name='imageUrl',
            field=models.URLField(default='https://cdn.discordapp.com/attachments/432564281113051136/952994827543404574/1355328252_2.gif'),
        ),
    ]
