# Generated by Django 4.0.3 on 2022-03-17 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_planet_imageurl_alter_star_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imageUrl', models.URLField(default='https://cdn.discordapp.com/attachments/432564281113051136/952994827543404574/1355328252_2.gif')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.body')),
            ],
        ),
        migrations.DeleteModel(
            name='Planet',
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
