# Generated by Django 4.0.3 on 2022-03-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_body_delete_planet_delete_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='parent',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.body'),
        ),
    ]
