# Generated by Django 4.0.3 on 2022-03-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_body_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='parent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.body'),
        ),
    ]
